//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class administators
{
    public int id { get; set; }
    public string admin_num { get; set; }
    public string admin_name { get; set; }
    public string admin_sex { get; set; }
    public int admin_age { get; set; }
    public string admin_password { get; set; }
    public string admin_type { get; set; }
    public string admin_phone { get; set; }
    public string admin_email { get; set; }
    public string admin_depart { get; set; }
}

public partial class resolution
{
    public int id { get; set; }
    public string resoluTitle { get; set; }
    public string resoluContent { get; set; }
    public string mainteach { get; set; }
    public string teach1 { get; set; }
    public string teach2 { get; set; }
    public System.DateTime puttime { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class teachDepart
{
    public int id { get; set; }
    public string teach_depart { get; set; }

    public virtual teachDepart teachDepart1 { get; set; }
    public virtual teachDepart teachDepart2 { get; set; }
}

public partial class teachers
{
    public int id { get; set; }
    public string teach_num { get; set; }
    public string teach_name { get; set; }
    public string teach_sex { get; set; }
    public int teach_age { get; set; }
    public string teach_password { get; set; }
    public string uesrType { get; set; }
    public string teach_phone { get; set; }
    public string teach_email { get; set; }
    public string teach_depart { get; set; }
}

public partial class userType
{
    public int id { get; set; }
    public string uesrType { get; set; }
}
