//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class resolutionManEntities : DbContext
{
    public resolutionManEntities()
        : base("name=resolutionManEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    public virtual DbSet<teachDepart> teachDepart { get; set; }
    public virtual DbSet<teachers> teachers { get; set; }
    public virtual DbSet<userType> userType { get; set; }
    public virtual DbSet<administators> administators { get; set; }
    public virtual DbSet<resolution> resolution { get; set; }
}
